### ISSUE TITLE
[question] why <style> does not appear twice?

### ISSUE THREAD

**Issue by nippur72** [planttheidea/react-style-tag#2]
Let me tell you this is really nice piece of code :-) 

I already do something similar in [rioct-cli](https://github.com/nippur72/rioct-cli) / [react-templates](https://github.com/wix/react-templates) (where the `<style>` tags are processed at compile time) but studying your code suggested me two or three improvements I can do, so a big thank you.

A question: I noticed the component generates a `<style>` tag that is also appended to the `document.head`. So I was expecting to find two style tags, one in the head and one in the component, but inspecting the DOM the one in the component is missing. How do you achieve that?

BTW, I would like to import your `minify(cssText)` function, is it going to stay? or perhaps can a module be made out of it?

One last remark: `npm run dev` fails in Windows, had to use instead:

```
node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --config=webpack.config.dev.js
```

**Comment by tquetano-r7** [comment]
Haha thank you for the kind words, flattery will get you everywhere. :)

In regards to the lack of a style tag in the body, this is actually a cool aspect of react 15+, that it you move the element via classic DOM appendchild it will continue to manage it regardless of its location in the document. If you check my code you'll see that I move the element on mount (which is cut and paste, not copy and paste), but requires an explicit removal on component will unmount. It's a neat trick, and works on any component.

For the minifyCss function i could abstract it to a separate function, but it'll take a couple days. I only have time for these personal libraries on the weekend, but it shouldn't be too crazy.

Thanks for the heads up on Windows, is hard for me to test since I'm a Linux guy. I'll try to update it to be more universal.

**Comment by planttheidea** [comment]
Sorry, I just realized I responded with my work account instead of my personal account. You can trust that guy, he's me. :)

**Comment by nippur72** [comment]
regarding the `minify()` modularization, it doesn't matter, as I am actually doing [this](https://github.com/nippur72/rioct-cli/commit/dff4da8c0df74e52f264cecb317dc481ad67bcd0#diff-445bbebb3309039f7de56f578afe1f81R3):

``` js
import { minify, prefixCss } from "react-style-tag/lib/transform";
```

**Comment by planttheidea** [comment]
Cool, I'm gonna close this then. Glad you were able to take advantage of that.

**Comment by planttheidea** [comment]
One additional note related to this, I have made the `minify` and `prefixCss` methods top-level exports in `1.2.1`, so now you can do ...

``` javascript
import {
  minifyCss,
  prefixCss
} from 'react-style-tag';
```

I named the `minify` export differently since it was no longer internal and should be explicit, but the original method name has been retained in the file you were referencing prior so as to prevent breakages if importing via the old way.
